CC = arm-none-linux-gnueabi-gcc
INCLUDES = ../include
LIBS = 
CFLAGS = -shared -fPIC -g -o

target:
	cp ../libinterface_device.a ./
	cp ../libdevice_controller.a ./
	cp ../libinterface_ui.a ./
	
	ar x libinterface_device.a
	ar x libdevice_controller.a
	ar x libinterface_ui.a
	
	ar cr libhmui_event.a *.o
	ranlib libhmui_event.a
	
	$(CC) $(CFLAGS) libhmui_event.so tempfile.c ./libhmui_event.a
	cp libhmui_event.so ../../bin
	cp libhmui_event.a ../../bin
	
	rm *.o *.a *.so

clean:
	rm *.o
